import streamlit as st
from groq import Groq
from sqlalchemy import create_engine, inspect
import pandas as pd
import plotly.express as px
from io import BytesIO
import ast
import os
import yaml
from dotenv import load_dotenv
import streamlit_authenticator as stauth
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import A4


st.set_page_config(page_title="Power AI", page_icon="🚀", layout="wide")

load_dotenv()

GROQ_API_KEY = os.getenv("GROQ_API_KEY")
MYSQL_USER = os.getenv("MYSQL_USER")
MYSQL_PASSWORD = os.getenv("MYSQL_PASSWORD")
MYSQL_HOST = os.getenv("MYSQL_HOST")


# -------------------------------------------------
# AUTHENTICATION
# -------------------------------------------------

with open("config.yaml", "r") as file:
    config = yaml.safe_load(file)

authenticator = stauth.Authenticate(
    config["credentials"],
    config["cookie"]["name"],
    config["cookie"]["key"],
    config["cookie"]["expiry_days"]
)

authenticator.login(location="main")

if st.session_state.get("authentication_status") is False:
    st.error("Username or password is incorrect")
    st.stop()

elif st.session_state.get("authentication_status") is None:
    st.warning("Please login first")
    st.stop()

elif st.session_state.get("authentication_status") is True:
    with st.sidebar:
        st.success(f"Welcome {st.session_state.get('name')}")
        authenticator.logout("Logout", "sidebar")


# -------------------------------------------------
# SESSION STATE
# -------------------------------------------------

default_states = {
    "chat_history": [],
    "last_sql_query": "",
    "last_result_df": None,
    "last_integrated_df": None,
    "last_mapping": {},
    "last_common_columns": [],
    "last_ai_summary": "",
    "last_integrated_summary": "",
    "last_file_summary": "",
    "uploaded_df": None
}

for key, value in default_states.items():
    if key not in st.session_state:
        st.session_state[key] = value


# -------------------------------------------------
# FUNCTIONS
# -------------------------------------------------

def clean_dataframe_columns(dataframe):
    dataframe = dataframe.copy()
    dataframe.columns = dataframe.columns.astype(str)

    dataframe = dataframe.loc[:, dataframe.columns != "nan"]
    dataframe = dataframe.loc[:, dataframe.columns != "None"]
    dataframe = dataframe.loc[:, ~dataframe.columns.str.contains("^Unnamed")]
    dataframe = dataframe.loc[:, ~dataframe.columns.duplicated()]
    dataframe = dataframe.dropna(axis=1, how="all")
    dataframe = dataframe.drop_duplicates()

    return dataframe


def convert_df_to_excel(dataframe):
    dataframe = clean_dataframe_columns(dataframe)
    output = BytesIO()

    with pd.ExcelWriter(output, engine="openpyxl") as writer:
        dataframe.to_excel(writer, index=False, sheet_name="Report")

    return output.getvalue()


def convert_df_to_pdf(dataframe, title="Power AI Report", summary_text=""):
    dataframe = clean_dataframe_columns(dataframe)

    output = BytesIO()
    doc = SimpleDocTemplate(output, pagesize=A4)
    styles = getSampleStyleSheet()
    elements = []

    elements.append(Paragraph(title, styles["Title"]))
    elements.append(Spacer(1, 12))
    elements.append(Paragraph("Generated by Power AI", styles["BodyText"]))
    elements.append(Spacer(1, 12))

    if summary_text:
        elements.append(Paragraph("AI Business Summary", styles["Heading2"]))
        elements.append(Paragraph(str(summary_text), styles["BodyText"]))
        elements.append(Spacer(1, 12))

    display_df = dataframe.head(50)
    data = [list(display_df.columns)] + display_df.astype(str).values.tolist()

    table = Table(data)
    elements.append(table)

    doc.build(elements)

    return output.getvalue()


def show_download_buttons(dataframe, file_prefix, display_name, summary_text=""):
    dataframe = clean_dataframe_columns(dataframe)

    col1, col2, col3 = st.columns(3)

    with col1:
        csv_data = dataframe.to_csv(index=False)

        st.download_button(
            label=f"Download {display_name} CSV",
            data=csv_data,
            file_name=f"{file_prefix}.csv",
            mime="text/csv"
        )

    with col2:
        excel_data = convert_df_to_excel(dataframe)

        st.download_button(
            label=f"Download {display_name} Excel",
            data=excel_data,
            file_name=f"{file_prefix}.xlsx",
            mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
        )

    with col3:
        pdf_data = convert_df_to_pdf(
            dataframe,
            title=f"{display_name} Report",
            summary_text=summary_text
        )

        st.download_button(
            label=f"Download {display_name} PDF",
            data=pdf_data,
            file_name=f"{file_prefix}.pdf",
            mime="application/pdf"
        )


def show_kpi_and_charts(dataframe, title):
    dataframe = clean_dataframe_columns(dataframe)

    numeric_columns = dataframe.select_dtypes(include=["int64", "float64"]).columns
    categorical_columns = dataframe.select_dtypes(include=["object"]).columns

    if len(numeric_columns) > 0:
        st.subheader(f"{title} KPI Insights")

        metric_columns = st.columns(3)

        for index, column in enumerate(numeric_columns):
            total_value = dataframe[column].sum()

            with metric_columns[index % 3]:
                st.metric(
                    label=f"Total {column}",
                    value=round(total_value, 2)
                )

    if len(categorical_columns) > 0 and len(numeric_columns) > 0:
        st.subheader(f"{title} Charts")

        fig_bar = px.bar(
            dataframe,
            x=categorical_columns[0],
            y=numeric_columns[0],
            title=f"{title} Bar Chart"
        )

        st.plotly_chart(fig_bar, use_container_width=True)

        fig_pie = px.pie(
            dataframe,
            names=categorical_columns[0],
            values=numeric_columns[0],
            title=f"{title} Pie Chart"
        )

        st.plotly_chart(fig_pie, use_container_width=True)

    if len(numeric_columns) > 0:
        fig_line = px.line(
            dataframe,
            y=numeric_columns[0],
            title=f"{title} Line Chart"
        )

        st.plotly_chart(fig_line, use_container_width=True)


def generate_ai_summary(client, title, user_query, dataframe):
    dataframe = clean_dataframe_columns(dataframe)

    summary_prompt = f"""
Explain this business data in simple English.

User Question:
{user_query}

Data:
{dataframe.head(30).to_string()}

Give short business insights.
"""

    summary_response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role": "user",
                "content": summary_prompt
            }
        ]
    )

    summary_text = summary_response.choices[0].message.content

    st.subheader(title)
    st.write(summary_text)

    return summary_text


def get_ai_column_mapping(db_columns, file_columns, client):
    mapping_prompt = f"""
You are a data integration assistant.

Match uploaded file columns to database columns.

Database Columns:
{db_columns}

Uploaded File Columns:
{file_columns}

Return ONLY a Python dictionary where:
- key = uploaded file column
- value = database column

Example:
{{
    "item_name": "product_name",
    "sales_amount": "revenue"
}}

Do not explain.
Do not use markdown.
"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role": "user",
                "content": mapping_prompt
            }
        ]
    )

    mapping_text = response.choices[0].message.content
    mapping_text = mapping_text.replace("```python", "")
    mapping_text = mapping_text.replace("```json", "")
    mapping_text = mapping_text.replace("```", "")
    mapping_text = mapping_text.strip()

    try:
        mapping = ast.literal_eval(mapping_text)

        if isinstance(mapping, dict):
            return mapping

        return {}

    except Exception:
        return {}


# -------------------------------------------------
# APP TITLE
# -------------------------------------------------

st.title("🚀 Power AI")
st.subheader("AI Conversational Business Intelligence System")


# -------------------------------------------------
# SIDEBAR DATABASE
# -------------------------------------------------

selected_db = st.sidebar.selectbox(
    "Select Database",
    ["power_ai", "sales_db", "hr_db"]
)


# -------------------------------------------------
# CONNECTIONS
# -------------------------------------------------

client = Groq(api_key=GROQ_API_KEY)

try:
    engine = create_engine(
        f"mysql+pymysql://{MYSQL_USER}:{MYSQL_PASSWORD}@{MYSQL_HOST}/{selected_db}"
    )

except Exception as e:
    st.error(f"MySQL Engine Error: {e}")
    st.stop()


# -------------------------------------------------
# SCHEMA DETECTION
# -------------------------------------------------

schema_text = ""

try:
    inspector = inspect(engine)
    tables = inspector.get_table_names()

    for table in tables:
        columns = inspector.get_columns(table)
        column_names = []

        for column in columns:
            column_names.append(column["name"])

        schema_text += f"""
{table}(
    {", ".join(column_names)}
)
"""

except Exception as e:
    st.error(f"Database Connection Error: {e}")


# -------------------------------------------------
# MAIN INPUT AREA
# -------------------------------------------------

user_query = st.text_input("Ask your business question")

uploaded_files = st.file_uploader(
    "Upload CSV or Excel Files",
    type=["csv", "xlsx"],
    accept_multiple_files=True
)


# -------------------------------------------------
# LOAD FILES
# -------------------------------------------------

if uploaded_files:
    dataframes = []

    for file in uploaded_files:
        try:
            if file.name.endswith(".csv"):
                temp_df = pd.read_csv(file)

            elif file.name.endswith(".xlsx"):
                temp_df = pd.read_excel(file)

            else:
                continue

            temp_df = clean_dataframe_columns(temp_df)
            temp_df["source_file"] = file.name
            dataframes.append(temp_df)

        except Exception as e:
            st.error(f"File Error in {file.name}: {e}")

    if len(dataframes) > 0:
        uploaded_df = pd.concat(dataframes, ignore_index=True)
        uploaded_df = clean_dataframe_columns(uploaded_df)
        st.session_state.uploaded_df = uploaded_df


uploaded_df = st.session_state.uploaded_df


# -------------------------------------------------
# ACTION BUTTONS
# -------------------------------------------------

col_btn1, col_btn2 = st.columns(2)

with col_btn1:
    analyze_files_clicked = st.button("Analyze Files")

with col_btn2:
    generate_clicked = st.button("Generate Insights")


# -------------------------------------------------
# FILE ANALYTICS LOGIC
# -------------------------------------------------

if analyze_files_clicked:
    if uploaded_df is None:
        st.error("Please upload CSV or Excel files first.")

    else:
        st.session_state.last_file_summary = generate_ai_summary(
            client,
            "AI File Business Summary",
            user_query,
            uploaded_df
        )


# -------------------------------------------------
# GENERATE DATABASE + INTEGRATED INSIGHTS
# -------------------------------------------------

if generate_clicked:
    if not user_query:
        st.error("Please enter a business question.")

    else:
        try:
            st.session_state.chat_history.append(
                {
                    "role": "user",
                    "message": user_query
                }
            )

            sql_prompt = f"""
You are a MySQL SQL generator.

Convert the user's question into ONLY a valid MySQL SELECT query.

Rules:
- Only generate SELECT queries
- Never generate INSERT, UPDATE, DELETE, DROP
- Return only SQL
- No markdown
- No explanations
- Use ORDER BY and LIMIT for highest values
- Use proper GROUP BY when needed
- Use only columns from this schema

Current Database:
{selected_db}

Database Schema:
{schema_text}

User Question:
{user_query}
"""

            messages = []

            for chat in st.session_state.chat_history:
                messages.append(
                    {
                        "role": chat["role"],
                        "content": chat["message"]
                    }
                )

            messages.append(
                {
                    "role": "user",
                    "content": sql_prompt
                }
            )

            response = client.chat.completions.create(
                model="llama-3.3-70b-versatile",
                messages=messages
            )

            sql_query = response.choices[0].message.content
            sql_query = sql_query.replace("```sql", "")
            sql_query = sql_query.replace("```", "")
            sql_query = sql_query.strip()

            st.session_state.last_sql_query = sql_query

            st.session_state.chat_history.append(
                {
                    "role": "assistant",
                    "message": sql_query
                }
            )

            if not sql_query.lower().startswith("select"):
                st.error("Only SELECT queries are allowed")

            else:
                df = pd.read_sql(sql_query, engine)
                df = clean_dataframe_columns(df)

                st.session_state.last_result_df = df

                st.session_state.last_ai_summary = generate_ai_summary(
                    client,
                    "AI Business Summary",
                    user_query,
                    df
                )

                st.session_state.last_integrated_df = None
                st.session_state.last_mapping = {}
                st.session_state.last_common_columns = []
                st.session_state.last_integrated_summary = ""

                if uploaded_df is not None:
                    mapping = get_ai_column_mapping(
                        list(df.columns),
                        list(uploaded_df.columns),
                        client
                    )

                    st.session_state.last_mapping = mapping

                    mapped_uploaded_df = uploaded_df.rename(columns=mapping)
                    mapped_uploaded_df = clean_dataframe_columns(mapped_uploaded_df)

                    common_columns = list(
                        set(df.columns).intersection(
                            set(mapped_uploaded_df.columns)
                        )
                    )

                    st.session_state.last_common_columns = common_columns

                    if len(common_columns) > 0:
                        merge_column = common_columns[0]

                        merged_df = pd.merge(
                            df,
                            mapped_uploaded_df,
                            on=merge_column,
                            how="inner",
                            suffixes=("_db", "_file")
                        )

                        merged_df = clean_dataframe_columns(merged_df)

                        st.session_state.last_integrated_df = merged_df

                        st.session_state.last_integrated_summary = generate_ai_summary(
                            client,
                            "AI Integrated Business Summary",
                            user_query,
                            merged_df
                        )

        except Exception as e:
            st.error(f"Database Error: {e}")


# -------------------------------------------------
# TABS UI
# -------------------------------------------------

tab1, tab2, tab3, tab4 = st.tabs(
    [
        "📊 Database Analytics",
        "📁 File Analytics",
        "🔗 Integrated Analytics",
        "💬 Chat History"
    ]
)


# -------------------------------------------------
# TAB 1 DATABASE ANALYTICS
# -------------------------------------------------

with tab1:
    st.header("📊 Database Analytics")

    if st.session_state.last_sql_query:
        st.subheader("Generated SQL")
        st.code(st.session_state.last_sql_query, language="sql")

    if st.session_state.last_result_df is not None:
        result_df = st.session_state.last_result_df

        st.subheader("Database Results")
        st.dataframe(result_df, use_container_width=True)

        show_download_buttons(
            result_df,
            "power_ai_results",
            "Database Results",
            st.session_state.last_ai_summary
        )

        show_kpi_and_charts(result_df, "Database")

        if st.session_state.last_ai_summary:
            st.subheader("AI Business Summary")
            st.write(st.session_state.last_ai_summary)

    else:
        st.info("Ask a business question and click Generate Insights.")


# -------------------------------------------------
# TAB 2 FILE ANALYTICS
# -------------------------------------------------

with tab2:
    st.header("📁 File Analytics")

    if uploaded_df is not None:
        st.subheader("Combined Uploaded File Data")
        st.dataframe(uploaded_df, use_container_width=True)

        show_download_buttons(
            uploaded_df,
            "uploaded_file_report",
            "Uploaded File",
            st.session_state.last_file_summary
        )

        show_kpi_and_charts(uploaded_df, "File")

        if st.session_state.last_file_summary:
            st.subheader("AI File Business Summary")
            st.write(st.session_state.last_file_summary)

        else:
            st.info("Click Analyze Files to generate AI file summary.")

    else:
        st.info("Upload CSV or Excel files to see file analytics.")


# -------------------------------------------------
# TAB 3 INTEGRATED ANALYTICS
# -------------------------------------------------

with tab3:
    st.header("🔗 Integrated Analytics")

    if st.session_state.last_mapping:
        st.subheader("AI Column Mapping")
        st.write(st.session_state.last_mapping)

    if st.session_state.last_common_columns:
        st.subheader("Common Columns")
        st.write(st.session_state.last_common_columns)

    if st.session_state.last_integrated_df is not None:
        integrated_df = st.session_state.last_integrated_df

        st.subheader("Integrated Data")
        st.dataframe(integrated_df, use_container_width=True)

        show_download_buttons(
            integrated_df,
            "integrated_data",
            "Integrated Data",
            st.session_state.last_integrated_summary
        )

        st.subheader("Missing Values")
        st.write(integrated_df.isnull().sum())

        show_kpi_and_charts(integrated_df, "Integrated")

        if st.session_state.last_integrated_summary:
            st.subheader("AI Integrated Business Summary")
            st.write(st.session_state.last_integrated_summary)

    elif st.session_state.last_mapping and not st.session_state.last_common_columns:
        st.warning("No matching columns found for integration.")

    else:
        st.info("Upload files and generate database insights to see integrated analytics.")


# -------------------------------------------------
# TAB 4 CHAT HISTORY
# -------------------------------------------------

with tab4:
    st.header("💬 Chat History")

    if st.session_state.chat_history:
        for chat in st.session_state.chat_history:
            st.write(f"{chat['role']}: {chat['message']}")

    else:
        st.info("No chat history yet.")