import streamlit as st
import pandas as pd
from io import BytesIO
from datetime import datetime

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib import colors

from utils.cleaner import clean_dataframe_columns
import re


# -------------------------------------------------
# EXCEL EXPORT
# -------------------------------------------------

def convert_df_to_excel(dataframe):

    dataframe = clean_dataframe_columns(dataframe)

    output = BytesIO()

    with pd.ExcelWriter(output, engine="openpyxl") as writer:
        dataframe.to_excel(
            writer,
            index=False,
            sheet_name="Report"
        )

    return output.getvalue()


# -------------------------------------------------
# PROFESSIONAL PDF EXPORT
# -------------------------------------------------
def clean_pdf_text(text):
    if not text:
        return ""

    text = str(text)

    # Remove markdown bold/italic symbols
    text = text.replace("**", "")
    text = text.replace("__", "")
    text = text.replace("* ", "• ")

    # Remove markdown heading symbols
    text = re.sub(r"#+\s*", "", text)

    # Fix excessive spaces
    text = re.sub(r"\s+", " ", text)

    return text.strip()

def convert_df_to_pdf(
    dataframe,
    title="Power AI Report",
    summary_text=""
):

    dataframe = clean_dataframe_columns(dataframe)

    output = BytesIO()

    doc = SimpleDocTemplate(
        output,
        pagesize=landscape(A4),
        rightMargin=20,
        leftMargin=20,
        topMargin=30,
        bottomMargin=30
    )

    styles = getSampleStyleSheet()
    elements = []

    generated_time = datetime.now().strftime("%d-%m-%Y %I:%M %p")

    # -------------------------------------------------
    # TITLE
    # -------------------------------------------------

    elements.append(
        Paragraph(title, styles["Title"])
    )

    elements.append(
        Spacer(1, 10)
    )

    elements.append(
        Paragraph(
            f"Generated by Power AI on {generated_time}",
            styles["BodyText"]
        )
    )

    elements.append(
        Spacer(1, 14)
    )

    # -------------------------------------------------
    # AI SUMMARY
    # -------------------------------------------------

    if summary_text:

        elements.append(
            Paragraph("AI Business Summary", styles["Heading2"])
        )

        elements.append(
            Paragraph(clean_pdf_text(summary_text), styles["BodyText"])
        )

        elements.append(
            Spacer(1, 14)
        )

    # -------------------------------------------------
    # DATA LIMIT FOR CLEAN PDF
    # -------------------------------------------------

    display_df = dataframe.head(30).copy()

    # Limit very long column names and values
    display_df.columns = [
        str(col)[:25] for col in display_df.columns
    ]

    for column in display_df.columns:
        display_df[column] = display_df[column].astype(str).str.slice(0, 35)

    data = [list(display_df.columns)] + display_df.values.tolist()

    # -------------------------------------------------
    # AUTO COLUMN WIDTH
    # -------------------------------------------------

    page_width = landscape(A4)[0] - 40

    column_count = len(display_df.columns)

    if column_count == 0:
        column_widths = []
    else:
        column_widths = [page_width / column_count] * column_count

    table = Table(
        data,
        colWidths=column_widths,
        repeatRows=1
    )

    # -------------------------------------------------
    # TABLE STYLE
    # -------------------------------------------------

    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e3a8a")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),

                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),

                ("FONTSIZE", (0, 0), (-1, 0), 8),
                ("FONTSIZE", (0, 1), (-1, -1), 7),

                ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
                ("TOPPADDING", (0, 0), (-1, 0), 8),

                ("GRID", (0, 0), (-1, -1), 0.4, colors.grey),

                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [
                    colors.white,
                    colors.HexColor("#f1f5f9")
                ]),
            ]
        )
    )

    elements.append(
        Paragraph("Report Data", styles["Heading2"])
    )

    elements.append(
        Spacer(1, 8)
    )

    elements.append(table)

    elements.append(
        Spacer(1, 12)
    )

    elements.append(
        Paragraph(
            "Note: PDF shows first 30 rows for clean formatting. Full data is available in CSV/Excel export.",
            styles["Italic"]
        )
    )

    doc.build(elements)

    return output.getvalue()


# -------------------------------------------------
# DOWNLOAD BUTTONS
# -------------------------------------------------

def show_download_buttons(
    dataframe,
    file_prefix,
    display_name,
    summary_text=""
):

    dataframe = clean_dataframe_columns(dataframe)

    col1, col2, col3 = st.columns(3)

    with col1:

        csv_data = dataframe.to_csv(index=False)

        st.download_button(
            label=f"Download {display_name} CSV",
            data=csv_data,
            file_name=f"{file_prefix}.csv",
            mime="text/csv"
        )

    with col2:

        excel_data = convert_df_to_excel(dataframe)

        st.download_button(
            label=f"Download {display_name} Excel",
            data=excel_data,
            file_name=f"{file_prefix}.xlsx",
            mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
        )

    with col3:

        pdf_data = convert_df_to_pdf(
            dataframe,
            title=f"{display_name} Report",
            summary_text=summary_text
        )

        st.download_button(
            label=f"Download {display_name} PDF",
            data=pdf_data,
            file_name=f"{file_prefix}.pdf",
            mime="application/pdf"
        )